#-------------------------------
#----DIA 1 CHEAT SHEET PYTHON-----
#-------------------------------

#imprimir hola mundo
print("hola mundooooo")

#DATOS PRIMITIVOA

#NUMERO

NUMERO = 1 #nombe variable = valor
print(NUMERO)#imprimir(tipo(variable))
print(type(NUMERO))

#DECIMAL

numeroDecimal =1.1
print(numeroDecimal)
print(type(numeroDecimal))

#booleano

miBooleano= True
print(miBooleano)
print(type(miBooleano))

#cadena de texto

texto="tibu linda"
print(texto)
print(type(texto))

#taller

#ingresa por teclado la informacio
print("hola como te llamas")
nombre=input()
print("cuantos años tienes")
edad=input()
print("hola ",nombre," tienes ",edad," años")

#conversion de tipos de variables 

print("numero entero para convertirlo a decimal")
f=(6)
print(float(f))

#
print("vamos a convertir un decimal a entero")
decimal=(1.5)
print(int(decimal))
print(type(decimal))

#
print("vamos a converti por medio de divisio")
division=5/2
print(division)

#bucles for y while
frutas = ["fresa","uva","manzana"]
for fruta in frutas:
    print(fruta)
    


#funciones (4tipos)

#desarrollado por jean franco guerrero acero - 